DROP TABLE IF EXISTS FILM_USER;
DROP TABLE IF EXISTS FILM_GENRE;
DROP TABLE IF EXISTS FRIENDSHIP;
DROP TABLE IF EXISTS USERS;
DROP TABLE IF EXISTS GENRES;
DROP TABLE IF EXISTS FILMS;
DROP TABLE IF EXISTS RATING;

CREATE TABLE IF NOT EXISTS PUBLIC.USERS (
	USER_ID INTEGER NOT NULL AUTO_INCREMENT,
	USER_EMAIL CHARACTER VARYING(255) NOT NULL,
	USER_LOGIN CHARACTER VARYING(255) NOT NULL,
	USER_NAME CHARACTER VARYING(255),
	USER_BIRTHDAY DATE NOT NULL,
	CONSTRAINT USERS_PK PRIMARY KEY (USER_ID)
);
CREATE TABLE IF NOT EXISTS PUBLIC.FRIENDSHIP (
	USER_FROM_ID INTEGER NOT NULL,
	USER_TO_ID INTEGER NOT NULL,
	STATUS BOOLEAN DEFAULT false NOT NULL,
	CONSTRAINT FRIENDSHIP_USERS_FK FOREIGN KEY (USER_FROM_ID) REFERENCES PUBLIC.USERS(USER_ID)
        ON DELETE CASCADE ON UPDATE CASCADE,
	CONSTRAINT FRIENDSHIP_USERS_FK_1 FOREIGN KEY (USER_TO_ID) REFERENCES PUBLIC.USERS(USER_ID)
        ON DELETE CASCADE ON UPDATE CASCADE
);
CREATE TABLE IF NOT EXISTS PUBLIC.RATING (
	RATING_ID INTEGER NOT NULL,
	RATING_NAME CHARACTER VARYING(200) NOT NULL,
	CONSTRAINT RATING_PK PRIMARY KEY (RATING_ID)
);
CREATE TABLE IF NOT EXISTS PUBLIC.GENRES (
	GENRE_ID INTEGER NOT NULL,
	GENRE_NAME CHARACTER VARYING(200) NOT NULL,
	CONSTRAINT GENRES_PK PRIMARY KEY (GENRE_ID)
);
CREATE TABLE IF NOT EXISTS PUBLIC.FILMS (
	FILM_ID INTEGER NOT NULL AUTO_INCREMENT,
	FILM_NAME CHARACTER VARYING(255) NOT NULL,
	DESCRIPTION CHARACTER VARYING(200),
	RELEASE_DATE DATE,
	DURATION INTEGER,
	RATING_ID INTEGER,
	CONSTRAINT FILMS_PK PRIMARY KEY (FILM_ID),
        CONSTRAINT FILMS_RATING_FK FOREIGN KEY (RATING_ID) REFERENCES PUBLIC.RATING(RATING_ID)
);
CREATE TABLE IF NOT EXISTS PUBLIC.FILM_GENRE (
	FILM_ID INTEGER NOT NULL,
	GENRE_ID INTEGER NOT NULL,
	CONSTRAINT FILM_GENRE_FILMS_FK FOREIGN KEY (FILM_ID) REFERENCES PUBLIC.FILMS(FILM_ID),
	CONSTRAINT FILM_GENRE_GENRES_FK FOREIGN KEY (GENRE_ID) REFERENCES PUBLIC.GENRES(GENRE_ID)
        ON DELETE CASCADE ON UPDATE CASCADE
);
CREATE TABLE IF NOT EXISTS PUBLIC.FILM_USER (
	FILM_ID INTEGER NOT NULL,
	USER_ID INTEGER NOT NULL,
	CONSTRAINT FILM_USER_FILMS_FK FOREIGN KEY (FILM_ID) REFERENCES PUBLIC.FILMS(FILM_ID)
        ON DELETE CASCADE ON UPDATE CASCADE,
	CONSTRAINT FILM_USER_USERS_FK FOREIGN KEY (USER_ID) REFERENCES PUBLIC.USERS(USER_ID)
        ON DELETE CASCADE ON UPDATE CASCADE
);